#!/bin/bash
. /etc/bash.bashrc;

echo "From anatomist_client " > /tmp/out_ana

CONTAINER_PYTHON=${1:-/casa/install/bin/python}
CONTAINER_ANA_DISPATCHER=${2:-/home/myuser/CASE/ana_dispatcher.py}
CONTAINER_ANA_LIB=${3:-/casa/install}
MASTERIP=${4:-11.0.0.11}
IS_ATLAS=${5:-false}

echo ${SINGULARITYID}; #export DISPLAY=:1;
export DISPLAY=$(pgrep -fa Xvfb | sed -e "s&.*:\([0-9]*\) .*&:\1&")
if ( ! ${IS_ATLAS} ); then
    OUT=$HOME/.vnc/out_ana
    COMMAND="PYTHONPATH=${CONTAINER_ANA_LIB}/python LD_LIBRARY_PATH=${CONTAINER_ANA_LIB}/lib:${LD_LIBRARY_PATH} ${CONTAINER_PYTHON} -- ${CONTAINER_ANA_DISPATCHER} --id anatomist-${SINGULARITYID} --url ${MASTERIP}"
else
    OUT=$HOME/.vnc/out_ana_atlas
    COMMAND="PYTHONPATH=${CONTAINER_ANA_LIB}/python LD_LIBRARY_PATH=${CONTAINER_ANA_LIB}/lib:${LD_LIBRARY_PATH} ${CONTAINER_PYTHON} -- ${CONTAINER_ANA_DISPATCHER} --id anatomist-atlas --url ${MASTERIP}"
fi
pwd >> $OUT
echo ${COMMAND} >> ${OUT}
eval ${COMMAND} 2>&1 |tee -a ${OUT} &

i=0
while [ true ]; do
    sleep 1
    grep 'ana_dispatcher ready\.' ${OUT}
    RET=$?
    if [ $RET -eq 0 ]; then
	break
    elif [ $i -gt 100 ]; then
	break
    fi
    i=$((i+1))
done
exit $RET
