#!/bin/bash
. /etc/bash.bashrc;

cd /home/myuser/CASE
CONTAINER_PYTHON=${1:-/casa/install/bin/python}
CONTAINER_ANA_DISPATCHER=${2:-/home/myuser/CASE/ana_dispatcher.py}
CONTAINER_ANA_LIB=${3:-/casa/install}

echo ${SINGULARITYID}; #export DISPLAY=:1;
export DISPLAY=$(pgrep -fa Xvfb | sed -e "s&.*:\([0-9]*\) .*&:\1&")

PYTHONPATH=${CONTAINER_ANA_LIB}/python LD_LIBRARY_PATH=${CONTAINER_ANA_LIB}/lib:${LD_LIBRARY_PATH} ${CONTAINER_PYTHON} -- ${CONTAINER_ANA_DISPATCHER} -b 2>&1 |tee $HOME/.vnc/out_anatomist_server &

sleep 2
i=0
while [ true ]; do
    sleep 1
    pgrep -fla ".*ana_dispatcher.py -b"
    RET=$?
    if [ $RET -eq 0 ]; then
	break
    elif [ $i -gt 100 ]; then
	break
    fi
    i=$((i+1))
done

exit $RET
